// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "gorm.io/plugin/soft_delete"

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID        int64                 `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	UserID    string                `gorm:"column:user_id;type:varchar(100);not null" json:"user_id"`
	Nickname  string                `gorm:"column:nickname;type:varchar(100)" json:"nickname"`
	Password  string                `gorm:"column:password;type:varchar(100)" json:"password"`
	Email     string                `gorm:"column:email;type:varchar(100)" json:"email"`
	CreatedAt int64                 `gorm:"column:created_at;type:bigint" json:"created_at"`
	UpdatedAt int64                 `gorm:"column:updated_at;type:bigint" json:"updated_at"`
	DeletedAt soft_delete.DeletedAt `gorm:"column:deleted_at;type:bigint" json:"-"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
