[system]
port=8088
host="127.0.0.1"

[mysql]
source="root:password@tcp(127.0.0.1:3306)/template"

[redis]
addr="127.0.0.1:6379"
username=""
password=""
db=0

[oss]
provider="aliyun"

[aliyun_oss]
endpoint=""
key_id=""
key_secret=""
bucket=""
region=""
role_arn = ""
domain = ""
