[system]
port = ":8088"
host="127.0.0.1"

[mysql]
source="root:password@tcp(127.0.0.1:3306)/template"

[redis]
addr="127.0.0.1:6379"
username=""
password=""
db=0

[oss]
provider="aliyun"

[aliyun_oss]
endpoint=""
key_id=""
key_secret=""
bucket=""
region=""
role_arn = ""
domain = ""

[log]
log_level = "debug"
encoding = "console"  # json or console
log_file_name = "./storage/logs/server.log"
max_backups = 30
max_age = 7
max_size = 1024
compress = true
